[book]
authors = ["Lucas"]
language = "de"
multilingual = false
src = "src"
title = "Algorithmen 1"

# enable support for math equations
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Luro02/algorithmen/"
additional-js = ["dist/highlight.js"]
