[book]
authors = ["Lucas"]
language = "de"
multilingual = false
src = "src"
title = "Algorithmen 1"

# enable support for math equations
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Luro02/algorithmen/"
additional-js = ["dist/highlight.js"]

[build]
create-missing = false

# use as mdbook preprocessor
[preprocessor.auto-gen-summary]
first-line-as-link-text = true # indicate mdbook to make the first line(default the file name) of markdown file as the link text in SUMMARY.md 

[output.html.fold]
enable = true
level = 0
