name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Setup mdbook-auto-gen-summary
        run: cargo install mdbook-auto-gen-summary

      - name: Setup yarn
        run: yarn install

      - name: Build Javascript
        run: yarn build

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./book
          cname: ${{ secrets.REPO_CNAME }}
          # keep_files: true
